<?php

namespace NDC\AnalyticsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use NDC\BlogBundle\Entity\Article;

/**
 * ViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewRepository extends EntityRepository
{
    /**
     * @param Article $article
     * @param string $groupBy MYSQL syntax for date format
     * @return array
     */
    public function articleStats(Article $article, $groupBy = '%j%y')
    {
        return $this->createQueryBuilder('v')
            ->select('DATE_FORMAT(v.createdAt, :groupBy) HIDDEN groupByDate, COUNT(DISTINCT v.sessionId) total, v.createdAt')
            ->setParameter('groupBy', $groupBy)
            ->where('v.article = :article')
            ->setParameter('article', $article)
            ->groupBy('groupByDate')
            ->orderBy('v.createdAt', 'ASC')
            ->getQuery()
            ->getResult(Query::HYDRATE_ARRAY);
    }
}
