<?php

namespace NDC\AnalyticsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use NDC\BlogBundle\Entity\Article;

/**
 * ViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewRepository extends EntityRepository
{
    public function articleStats(Article $article)
    {
        return $this->createQueryBuilder('v')
            ->groupBy('v.sessionId')
            ->getQuery()
            ->getResult(Query::HYDRATE_ARRAY);
    }
}
