services:
    ndc_blog.date_extension:
        class: NDC\BlogBundle\Twig\DateExtension
        arguments:
            - @translator
        tags:
            - { name: twig.extension }

    ndc_blog.comment_extension:
        class: NDC\BlogBundle\Twig\CommentExtension
        tags:
            - { name: twig.extension }

    validator.allowed_username:
        class: NDC\BlogBundle\Validator\Constraints\AllowedUsernameValidator
        arguments:
            - @doctrine.orm.entity_manager
            - @security.context
        tags:
            - { name: validator.constraint_validator, alias: allowed_username }