NDC\BlogBundle\Entity\Article:
    type: entity
    table: ndc_article
    repositoryClass: NDC\BlogBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255

        slug:
            type: string
            length: 255
            gedmo:
                slug:
                    fields:
                        - title

        createdAt:
            column: created_at
            type: datetime
            gedmo:
                timestampable:
                    on: create

        updatedAt:
            column: updated_at
            type: datetime
            gedmo:
                timestampable:
                    on: update

        html:
            type: text

        state:
            type: string
            length: 20

        views:
            type: integer
            options:
                unsigned:
                    true

    manyToOne:
        author:
            targetEntity: NDC\UserBundle\Entity\User
            fetch: EAGER
            nullable: false
            gedmo:
                blameable:
                    on: create

        category:
            targetEntity: NDC\BlogBundle\Entity\Category
            fetch: EAGER
            nullable: false

    manyToMany:
        tech:
            targetEntity: NDC\BlogBundle\Entity\Tech
            fetch: EAGER
            joinTable:
                name: ndc_article_tech
                joinColumns:
                    article_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tech_id:
                        referencedColumnName: id

    oneToMany:
        comments:
            targetEntity: NDC\BlogBundle\Entity\Comment
            mappedBy: article

    oneToOne:
        demo:
            targetEntity: NDC\BlogBundle\Entity\Demo
            mappedBy: article
            fetch: EAGER