NDC\BlogBundle\Entity\Category:
    type: entity
    table: ndc_category
    repositoryClass: NDC\BlogBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 50

        abbr:
            type: string
            length: 4

        slug:
            type: string
            length: 50
            gedmo:
                slug:
                    fields:
                        - name

        color:
            type: string
            length: 6

        txtColor:
            type: string
            length: 6
            column: txt_color
