NDC\BlogBundle\Entity\Comment:
    type: entity
    table: ndc_comment
    repositoryClass: NDC\BlogBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 50

        email:
            type: string
            length: 255

        message:
            type: text

        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create

        isRegistered:
            column: is_registered
            type: boolean

    manyToOne:
        article:
            targetEntity: NDC\BlogBundle\Entity\Article
            fetch: EAGER
            nullable: false
            inversedBy: comments
