blog_category_admin_index:
    pattern: /
    defaults: { _controller: NDCBlogBundle:CategoryAdmin:index }

blog_category_admin_add:
    pattern: /add
    defaults: { _controller: NDCBlogBundle:CategoryAdmin:add }

blog_category_admin_edit:
    pattern: /{id}/edit
    defaults: { _controller: NDCBlogBundle:CategoryAdmin:edit }