blog_demo_admin_index:
    pattern: /
    defaults: { _controller: NDCBlogBundle:DemoAdmin:index }

blog_demo_admin_add:
    pattern: /add
    defaults: { _controller: NDCBlogBundle:DemoAdmin:add }

blog_demo_admin_edit:
    pattern: /{id}/edit
    defaults: { _controller: NDCBlogBundle:DemoAdmin:edit }