blog_image_admin_index:
    pattern: /
    defaults: { _controller: NDCBlogBundle:ImageAdmin:index }

blog_image_admin_browse:
    pattern: /browse
    defaults: { _controller: NDCBlogBundle:ImageAdmin:browse }

blog_image_admin_upload:
    pattern: /upload
    methods: post
    defaults: { _controller: NDCBlogBundle:ImageAdmin:upload }