<?php

namespace NDC\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function queryAll()
    {
        return $this->createQueryBuilder('a')
            ->orderBy('a.createdAt', 'DESC');
    }

    public function queryAllNotDraft()
    {
        return $this->createQueryBuilder('a')
            ->where('a.state != :state')
            ->setParameter('state', 'draft')
            ->orderBy('a.createdAt', 'DESC');
    }

    public function queryAllPublished()
    {
        return $this->createQueryBuilder('a')
            ->where('a.state = :state')
            ->setParameter('state', 'published')
            ->orderBy('a.createdAt', 'DESC');
    }
}
