<?php

namespace NDC\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function queryAll()
    {
        return $this->createQueryBuilder('c')
            ->orderBy('c.name');
    }

    public function findAllSlug()
    {
        $r = $this->createQueryBuilder('c')
            ->select('c.slug')
            ->getQuery()
            ->getArrayResult();

        $result = array();
        foreach($r as $l)
            $result[] = $l['slug'];

        return $result;
    }
}
