<?php

namespace NDC\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use NDC\BlogBundle\Entity\Article;
use NDC\UserBundle\Entity\User;

/**
 * CommentMonitoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentMonitoringRepository extends EntityRepository
{
    public function findOne(Article $article, User $user)
    {
        try{
            return $this->createQueryBuilder('cm')
                ->where('cm.article = :article')
                ->setParameter('article', $article)
                ->andWhere('cm.user = :user')
                ->setParameter('user', $user)
                ->getQuery()
                ->getSingleResult();
        }catch(NoResultException $e){
            return null;
        }
    }
}
