<?php

namespace NDC\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;
use NDC\UserBundle\Entity\User;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findUnseen(User $user)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('c')
            ->from($this->_entityName, 'c')
            ->innerJoin('c.article', 'a')
            ->innerJoin('NDCBlogBundle:CommentMonitoring', 'cm', Join::WITH, 'cm.article = a')
            ->where('cm.user = :user')
            ->andWhere('c.createdAt > cm.lastViewed')
            ->setParameter('user', $user)
            ->orderBy('a.id', 'DESC')
            ->addOrderBy('c.createdAt', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
