<?php

namespace NDC\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use NDC\BlogBundle\Entity\Article;

/**
 * DemoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemoRepository extends EntityRepository
{
    public function queryAll()
    {
        return $this->createQueryBuilder('d')
            ->orderBy('d.createdAt', 'DESC');
    }

    public function queryDemoWithoutArticle(Article $article)
    {
        $results = $this->createQueryBuilder('d')
            ->leftJoin('d.article', 'a')
            ->where('a.id IS NULL')
            ->orderBy('d.createdAt', 'DESC');
        if (isset($article)) {
            $results->orWhere('a.id = :id')->setParameter('id', $article->getId());
        }
        return $results;
    }
}
