<?php

namespace NDC\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    public function queryAll()
    {
        return $this->createQueryBuilder('i')
            ->orderBy('i.id', 'DESC');
    }
}
